import streamlit as st
import requests

st.set_page_config(page_title="AI Text Summarizer Demo", page_icon="📝")

st.title("AI Text Summarizer Demo")
st.write("Enter your text below to get a concise summary generated by the Pegasus model.")

# Text input from user
text = st.text_area("Enter text to summarize", height=200)

if st.button("Summarize"):
    if not text.strip():
        st.warning("Please enter some text to summarize.")
    else:
        with st.spinner('Summarizing...'):
            try:
                # Make POST request to your FastAPI backend
                response = requests.post("http://localhost:8081/predict", json={"text": text})
                response.raise_for_status()
                data = response.json()

                if 'summary' in data:
                    st.success("Summary:")
                    st.write(data['summary'])
                elif 'error' in data:
                    st.error(f"Error from API: {data['error']}")
                else:
                    st.error("Unexpected response from server.")

            except requests.exceptions.RequestException as e:
                st.error(f"Request failed: {e}")
